export const language_list = [
  { value: "ace_Arab", label: "Achinese (Arabic)" },
  { value: "ace_Latn", label: "Achinese (Latin)" },
  { value: "acm_Arab", label: "Armenian (Arabic)" },
  { value: "acq_Arab", label: "Ta'izzi-Adeni Arabic (Arabic)" },
  { value: "aeb_Arab", label: "Tunisian Arabic (Arabic)" },
  { value: "afr_Latn", label: "Afrikaans (Latin)" },
  { value: "ajp_Arab", label: "South Azerbaijani (Arabic)" },
  { value: "aka_Latn", label: "Akan (Latin)" },
  { value: "amh_Ethi", label: "Amharic (Ethiopic)" },
  { value: "apc_Arab", label: "North Levantine Arabic (Arabic)" },
  { value: "arb_Arab", label: "Standard Arabic (Arabic)" },
  { value: "ars_Arab", label: "Najdi Arabic (Arabic)" },
  { value: "ary_Arab", label: "Moroccan Arabic (Arabic)" },
  { value: "arz_Arab", label: "Egyptian Arabic (Arabic)" },
  { value: "asm_Beng", label: "Assamese (Bengali)" },
  { value: "ast_Latn", label: "Asturian (Latin)" },
  { value: "awa_Deva", label: "Awadhi (Devanagari)" },
  { value: "ayr_Latn", label: "Aymara (Latin)" },
  { value: "azb_Arab", label: "South Azerbaijani (Arabic)" },
  { value: "azj_Latn", label: "North Azerbaijani (Latin)" },
  { value: "bak_Cyrl", label: "Azerbaijani (Cyrillic)" },
  { value: "bam_Latn", label: "Bambara (Latin)" },
  { value: "ban_Latn", label: "Balinese (Latin)" },
  { value: "bel_Cyrl", label: "Belarusian (Cyrillic)" },
  { value: "bem_Latn", label: "Bemba (Latin)" },
  { value: "ben_Beng", label: "Bengali (Bengali)" },
  { value: "bho_Deva", label: "Bhojpuri (Devanagari)" },
  { value: "bjn_Arab", label: "Banjar (Arabic)" },
  { value: "bjn_Latn", label: "Banjar (Latin)" },
  { value: "bod_Tibt", label: "Tibetan (Tibetan)" },
  { value: "bos_Latn", label: "Bosnian (Latin)" },
  { value: "bug_Latn", label: "Buginese (Latin)" },
  { value: "bul_Cyrl", label: "Bulgarian (Cyrillic)" },
  { value: "cat_Latn", label: "Catalan (Latin)" },
  { value: "ceb_Latn", label: "Cebuano (Latin)" },
  { value: "ces_Latn", label: "Czech (Latin)" },
  { value: "cjk_Latn", label: "Chinese (Latin)" },
  { value: "ckb_Arab", label: "Kurdish (Central Kurdish) (Arabic)" },
  { value: "crh_Latn", label: "Crimean Tatar (Latin)" },
  { value: "cym_Latn", label: "Welsh (Latin)" },
  { value: "dan_Latn", label: "Danish (Latin)" },
  { value: "deu_Latn", label: "German (Latin)" },
  { value: "dik_Latn", label: "Dinka (Latin)" },
  { value: "dyu_Latn", label: "Dyula (Latin)" },
  { value: "dzo_Tibt", label: "Dzongkha (Tibetan)" },
  { value: "ell_Grek", label: "Greek (Greek)" },
  { value: "eng_Latn", label: "English (Latin)" },
  { value: "epo_Latn", label: "Esperanto (Latin)" },
  { value: "est_Latn", label: "Estonian (Latin)" },
  { value: "eus_Latn", label: "Basque (Latin)" },
  { value: "ewe_Latn", label: "Ewe (Latin)" },
  { value: "fao_Latn", label: "Faroese (Latin)" },
  { value: "pes_Arab", label: "Persian (Arabic)" },
  { value: "fij_Latn", label: "Fijian (Latin)" },
  { value: "fin_Latn", label: "Finnish (Latin)" },
  { value: "fon_Latn", label: "Fon (Latin)" },
  { value: "fra_Latn", label: "French (Latin)" },
  { value: "fur_Latn", label: "Friulian (Latin)" },
  { value: "fuv_Latn", label: "Nigerian Fulfulde (Latin)" },
  { value: "gla_Latn", label: "Gaelic (Latin)" },
  { value: "gle_Latn", label: "Irish (Latin)" },
  { value: "glg_Latn", label: "Galician (Latin)" },
  { value: "grn_Latn", label: "Guarani (Latin)" },
  { value: "guj_Gujr", label: "Gujarati (Gujarati)" },
  { value: "hat_Latn", label: "Haitian Creole (Latin)" },
  { value: "hau_Latn", label: "Hausa (Latin)" },
  { value: "heb_Hebr", label: "Hebrew (Hebrew)" },
  { value: "hin_Deva", label: "Hindi (Devanagari)" },
  { value: "hne_Deva", label: "Chhattisgarhi (Devanagari)" },
  { value: "hrv_Latn", label: "Croatian (Latin)" },
  { value: "hun_Latn", label: "Hungarian (Latin)" },
  { value: "hye_Armn", label: "Armenian (Armenian)" },
  { value: "ibo_Latn", label: "Igbo (Latin)" },
  { value: "ilo_Latn", label: "Ilocano (Latin)" },
  { value: "ind_Latn", label: "Indonesian (Latin)" },
  { value: "isl_Latn", label: "Icelandic (Latin)" },
  { value: "ita_Latn", label: "Italian (Latin)" },
  { value: "jav_Latn", label: "Javanese (Latin)" },
  { value: "jpn_Jpan", label: "Japanese (Japanese)" },
  { value: "kab_Latn", label: "Kabyle (Latin)" },
  { value: "kac_Latn", label: "Kachin (Latin)" },
  { value: "kam_Latn", label: "Kamba (Latin)" },
  { value: "kan_Knda", label: "Kannada (Kannada)" },
  { value: "kas_Arab", label: "Kashmiri (Arabic)" },
  { value: "kas_Deva", label: "Kashmiri (Devanagari)" },
  { value: "kat_Geor", label: "Georgian (Georgian)" },
  { value: "knc_Arab", label: "Konkani (Arabic)" },
  { value: "knc_Latn", label: "Konkani (Latin)" },
  { value: "kaz_Cyrl", label: "Kazakh (Cyrillic)" },
  { value: "kbp_Latn", label: "Kabiye (Latin)" },
  { value: "kea_Latn", label: "Kabuverdianu (Latin)" },
  { value: "khm_Khmr", label: "Khmer (Khmer)" },
  { value: "kik_Latn", label: "Kikuyu (Latin)" },
  { value: "kin_Latn", label: "Kinyarwanda (Latin)" },
  { value: "kir_Cyrl", label: "Kyrgyz (Cyrillic)" },
  { value: "kmb_Latn", label: "Kimbundu (Latin)" },
  { value: "kon_Latn", label: "Congo (Latin)" },
  { value: "kor_Hang", label: "Korean (Hangul)" },
  { value: "kmr_Latn", label: "Khmer (Latin)" },
  { value: "lao_Laoo", label: "Lao (Lao)" },
  { value: "lvs_Latn", label: "Latvian (Latin)" },
  { value: "lij_Latn", label: "Ligurian (Latin)" },
  { value: "lim_Latn", label: "Limburgish (Latin)" },
  { value: "lin_Latn", label: "Lingala (Latin)" },
  { value: "lit_Latn", label: "Lithuanian (Latin)" },
  { value: "lmo_Latn", label: "Lombard (Latin)" },
  { value: "ltg_Latn", label: "Latgalian (Latin)" },
  { value: "ltz_Latn", label: "Luxembourgish (Latin)" },
  { value: "lua_Latn", label: "Luba-Lulua (Latin)" },
  { value: "lug_Latn", label: "Ganda (Latin)" },
  { value: "luo_Latn", label: "Luo (Latin)" },
  { value: "lus_Latn", label: "Mizo (Latin)" },
  { value: "mag_Deva", label: "Magahi (Devanagari)" },
  { value: "mai_Deva", label: "Maithili (Devanagari)" },
  { value: "mal_Mlym", label: "Malayalam (Malayalam)" },
  { value: "mar_Deva", label: "Marathi (Devanagari)" },
  { value: "min_Latn", label: "Minangkabau (Latin)" },
  { value: "mkd_Cyrl", label: "Macedonian (Cyrillic)" },
  { value: "plt_Latn", label: "Maltese (Latin)" },
  { value: "mlt_Latn", label: "Maltese (Latin)" },
  { value: "mni_Beng", label: "Manipuri (Bengali)" },
  { value: "khk_Cyrl", label: "Khalkha Mongolian (Cyrillic)" },
  { value: "mos_Latn", label: "Mossi (Latin)" },
  { value: "mri_Latn", label: "Maori (Latin)" },
  { value: "zsm_Latn", label: "Standard Malay (Latin)" },
  { value: "mya_Mymr", label: "Burmese (Burmese)" },
  { value: "nld_Latn", label: "Dutch (Latin)" },
  { value: "nno_Latn", label: "Norwegian Nynorsk (Latin)" },
  { value: "nob_Latn", label: "Norwegian Bokmål (Latin)" },
  { value: "npi_Deva", label: "Nepali (Devanagari)" },
  { value: "nso_Latn", label: "Northern Sotho (Latin)" },
  { value: "nus_Latn", label: "Nuer (Latin)" },
  { value: "nya_Latn", label: "Nyanja (Latin)" },
  { value: "oci_Latn", label: "Occitan (Latin)" },
  { value: "gaz_Latn", label: "Ga (Latin)" },
  { value: "ory_Orya", label: "Odia (Odia)" },
  { value: "pag_Latn", label: "Pangasinan (Latin)" },
  { value: "pan_Guru", label: "Punjabi (Gurmukhi)" },
  { value: "pap_Latn", label: "Papiamentu (Latin)" },
  { value: "pol_Latn", label: "Polish (Latin)" },
  { value: "por_Latn", label: "Portuguese (Latin)" },
  { value: "prs_Arab", label: "Persian (Arabic)" },
  { value: "pbt_Arab", label: "Pashtu (Arabic)" },
  { value: "quy_Latn", label: "Quechua (Latin)" },
  { value: "ron_Latn", label: "Romanian (Latin)" },
  { value: "run_Latn", label: "Rundi (Latin)" },
  { value: "rus_Cyrl", label: "Russian (Cyrillic)" },
  { value: "sag_Latn", label: "Samburu (Latin)" },
  { value: "san_Deva", label: "Sanskrit (Devanagari)" },
  { value: "sat_Beng", label: "Santali (Bengali)" },
  { value: "scn_Latn", label: "Sicilian (Latin)" },
  { value: "shn_Mymr", label: "Shan (Burmese)" },
  { value: "sin_Sinh", label: "Sinhala (Sinhala)" },
  { value: "slk_Latn", label: "Slovak (Latin)" },
  { value: "slv_Latn", label: "Slovenian (Latin)" },
  { value: "smo_Latn", label: "Samoan (Latin)" },
  { value: "sna_Latn", label: "Shona (Latin)" },
  { value: "snd_Arab", label: "Sindhi (Arabic)" },
  { value: "som_Latn", label: "Somali (Latin)" },
  { value: "sot_Latn", label: "Southern Sotho (Latin)" },
  { value: "spa_Latn", label: "Spanish (Latin)" },
  { value: "als_Latn", label: "Alsatian (Latin)" },
  { value: "srd_Latn", label: "Sardinian (Latin)" },
  { value: "srp_Cyrl", label: "Serbian (Cyrillic)" },
  { value: "ssw_Latn", label: "Swati (Latin)" },
  { value: "sun_Latn", label: "Sundanese (Latin)" },
  { value: "swe_Latn", label: "Swedish (Latin)" },
  { value: "swh_Latn", label: "Swahili (Latin)" },
  { value: "szl_Latn", label: "Silesian (Latin)" },
  { value: "tam_Taml", label: "Tamil (Tamil)" },
  { value: "tat_Cyrl", label: "Tatar (Cyrillic)" },
  { value: "tel_Telu", label: "Telugu (Telugu)" },
  { value: "tgk_Cyrl", label: "Tajik (Cyrillic)" },
  { value: "tgl_Latn", label: "Tagalog (Latin)" },
  { value: "tha_Thai", label: "Thai (Thai)" },
  { value: "tir_Ethi", label: "Tigrinya (Ethiopic)" },
  { value: "taq_Latn", label: "Taqi Damili (Latin)" },
  { value: "taq_Tfng", label: "Taqi Damili (Tifinagh)" },
  { value: "tpi_Latn", label: "Tok Pisin (Latin)" },
  { value: "tsn_Latn", label: "Tswana (Latin)" },
  { value: "tso_Latn", label: "Tsonga (Latin)" },
  { value: "tuk_Latn", label: "Turkmen (Latin)" },
  { value: "tum_Latn", label: "Tumbuka (Latin)" },
  { value: "tur_Latn", label: "Turkish (Latin)" },
  { value: "twi_Latn", label: "Twi (Latin)" },
  { value: "tzm_Tfng", label: "Central Atlas Tamazight (Tifinagh)" },
  { value: "uig_Arab", label: "Uyghur (Arabic)" },
  { value: "ukr_Cyrl", label: "Ukrainian (Cyrillic)" },
  { value: "umb_Latn", label: "Umbundu (Latin)" },
  { value: "urd_Arab", label: "Urdu (Arabic)" },
  { value: "uzn_Latn", label: "Uzbek (Latin)" },
  { value: "vec_Latn", label: "Venetian (Latin)" },
  { value: "vie_Latn", label: "Vietnamese (Latin)" },
  { value: "war_Latn", label: "Waray (Latin)" },
  { value: "wol_Latn", label: "Wolof (Latin)" },
  { value: "xho_Latn", label: "Xhosa (Latin)" },
  { value: "ydd_Hebr", label: "Eastern Yiddish (Hebrew)" },
  { value: "yor_Latn", label: "Yoruba (Latin)" },
  { value: "yue_Hant", label: "Cantonese (Traditional Han)" },
  { value: "zho_Hans", label: "Chinese (Simplified Han)" },
  { value: "zho_Hant", label: "Chinese (Traditional Han)" },
  { value: "zul_Latn", label: "Zulu (Latin)" },
];
